[profiles]
ca-certificates = { packages = ["ca-certificates"] }
curl = { packages = ["curl"] }
git = { packages = ["git"] }
gzip = { packages = ["gzip"] }
tar = { packages = ["tar"] }
vim = { packages = ["vim"] }

[profiles.ssh-server]
packages = ["ssh-server"]

[profiles.ssh-server.services.ssh-server]
target = "system"
packages = ["ssh-server"]
enabled = true
running = true

[profiles.bootstrap-cli]
include = [
  { profile = "ca-certificates" },
  { profile = "curl" },
  { profile = "git" },
  { profile = "gzip" },
  { profile = "tar" },
  { profile = "vim" },
]
