[package.zypper]
"core:ca-certificates" = ["ca-certificates"]
"core:curl" = ["curl"]
"core:git" = ["git"]
"core:gzip" = ["gzip"]
"core:tar" = ["tar"]
"core:vim" = ["vim"]
"core:ssh-server" = ["openssh-server"]

[package.apk]
"core:ca-certificates" = ["ca-certificates"]
"core:curl" = ["curl"]
"core:git" = ["git"]
"core:gzip" = ["gzip"]
"core:tar" = ["tar"]
"core:vim" = ["vim"]
"core:ssh-server" = ["openssh-server"]

[service.systemd]
"core:ssh-server" = ["sshd.service"]

[service.openrc]
"core:ssh-server" = ["sshd"]
